# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0d60f8c2eaa4908e8779c74a4e594b950582fea9e3b7dd5e05d1bdefaf7c28cce388c253ad5135639bb0908dcefb5e01492b20d9e2819477368468ab7b8531

test:
  secret_key_base: af9261d8ab33dc5d2019288a84fb3ee2dcb9e0456fd0b365e55ff8693015bdeeef4aab8d8c3440662dd63f4b98f15d13cff77cddeeee6549ffce80efdf0a5302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
